global: 
  smtp_smarthost: 'smtp.163.com:465'
  smtp_from: 'jxl@163.com'
  smtp_auth_username: 'jxl@163.com'
  smtp_auth_password: '123456'
  smtp_require_tls: false
  #resolve_timeout: 5m


templates:
  - '/etc/alertmanager/alert.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 30s 
  repeat_interval: 30m
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'leader'
    continue: true
  - match_re:
      severity: ^(warning|critical)$
      user: ^(jxls)$
    receiver: 'ops'

receivers:
  - name: 'email'
    email_configs:
    - to: 'jiangxianliang@xxx.com'
      html: '{{ template "email.alert.html" . }}'
      headers: { Subject: 'Project name : {{ template "__subject" . }}' }
      send_resolved: true

  - name: 'leader'
    email_configs:
    - to: 'jiangxianliang@xxx.com'
      html: '{{ template "email.alert.html" . }}'
      headers: { Subject: 'Leader Project name : {{ template "__subject" . }}' }
      send_resolved: true

  - name: 'ops'
    email_configs:
    - to: 'jiangxianliang@xxx.com'
      html: '{{ template "email.alert.html" . }}'
      headers: { Subject: 'Ops Project name : {{ template "__subject" . }}' }
      send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
